npc-dealers:
  '99':
    type: BUY
  '100':
    type: SELL
vanilla:
  auto-replant:
    enabled: false
    blacklist:
    - 'WHEAT'
    ignore-drug-plants: true
  drops:
    '1':
      type: BLOCK
      permission: 'ultimatedrugs.vanilla-drops.1'
      override-drops: true
      override-exp: false
      blocks:
        '1':
          type: STONE
        '2':
          type: GRASS_BLOCK
          data:
          - 'snowy=false'
      drops:
        '1':
          item:
            type: STONE
            display-name: '&7Default Stone'
        '2':
          item:
            type: SPONGE
            display-name: '&bMagic Sponge'
            lore:
            - '&7This sponge is magic!'
    '2':
      type: MOB
      override-drops: false
      override-exp: true
      entity-types:
      - 'ZOMBIE'
      drops:
        '1':
          item:
            type: REDSTONE
            display-name: '&cZombie Redstone'
          min-amount: 2
          max-amount: 5
          drop-chance: 50.0
    '3':
      type: FISHING
      override-drops: false
      override-exp: false
      fish-types:
      - 'COD'
      - 'SALMON'
      - 'PUFFERFISH'
      drops:
        '1':
          item:
            type: DIRT
            display-name: '&bSea Dirt'
          drop-chance: 50.0
fertilizers:
  'sample':
    item:
      type: STONE
      display-name: '&eSample Stone'
    grow-amount: 1
    drug-ids:
    - 'weed'