name: UltimateDrugs
version: 2.3.4
api-version: 1.13
author: Dexuby
main: me.dexuby.UltimateDrugs.Main
depend: [Vault]
softdepend: [WorldEdit, WorldGuard, CrackShot, Jobs, Citizens, ProtocolLib]
commands:
  drugs:
    usage: /<command>
    aliases: [dr]